[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

# Redirect /api/* to the appropriate function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
